---
- name: Install Elasticsearch
  hosts: elastic
  become: yes

  tasks:
    - name: Include Docker setup
      include_tasks: common_docker.yml
      when: "'docker_hosts' in group_names"

    - name: Increase vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: Run Elasticsearch container
      docker_container:
        name: elasticsearch
        image: elastic/elasticsearch:7.17.13
        env:
          discovery.type: "single-node"
          ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        ulimits:
          - "memlock:-1:-1"
        ports:
          - "9200:9200"
        volumes:
          - "esdata:/usr/share/elasticsearch/data"
        restart_policy: always