---
- name: Install Filebeat on web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: ["docker.io", "docker-compose-plugin"]
        state: present
        update_cache: yes

    - name: Create Filebeat config directory
      file:
        path: /etc/filebeat
        state: directory
        mode: '0755'

    - name: Configure Filebeat
      copy:
        content: |
          filebeat.inputs:
          - type: log
            enabled: true
            paths:
              - "/var/log/nginx/access.log"
              - "/var/log/nginx/error.log"

          output.elasticsearch:
            hosts: ["10.0.1.20:9200"]
        dest: /etc/filebeat/filebeat.yml

    - name: Run Filebeat container
      docker_container:
        name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.13
        volumes:
          - "/etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
          - "/var/log/nginx:/var/log/nginx:ro"
        restart_policy: always
      when: "'elastic' in groups"