---
- name: Install and configure Grafana
  hosts: grafana
  become: yes

  tasks:
    - name: Include Docker setup
      include_tasks: common_docker.yml

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        ports:
          - "3000:3000"
        volumes:
          - "grafana-storage:/var/lib/grafana"
        restart_policy: always