---
- name: Install Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Include Docker setup
      include_tasks: common_docker.yml

    - name: Run Kibana container
      docker_container:
        name: kibana
        image: elastic/kibana:7.17.13
        env:
          ELASTICSEARCH_HOSTS: "http://10.0.1.20:9200"
        ports:
          - "5601:5601"
        restart_policy: always