---
- name: Install Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: ["docker.io", "docker-compose-plugin"]
        state: present
        update_cache: yes

    - name: Run Kibana container
      docker_container:
        name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.13
        env:
          ELASTICSEARCH_HOSTS: "http://10.0.1.20:9200"
        ports:
          - "5601:5601"
        restart_policy: always
      when: "'elastic' in groups"