---
# Файл с задачами для Nginx (должен включаться через include_tasks)
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx status page
  copy:
    content: |
      server {
          listen 80;
          location /nginx_status {
              stub_status on;
              access_log off;
              allow 127.0.0.1;
              deny all;
          }
      }
    dest: /etc/nginx/conf.d/status.conf
    mode: '0644'

- name: Restart Nginx
  service:
    name: nginx
    state: restarted