---
- hosts: prometheus
  become: yes
  name: Install Prometheus
  tasks:
    - name: Include Docker setup
      include_tasks: common_docker.yml

    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Configure Prometheus
      copy:
        content: |
          global:
            scrape_interval: 15s
            
          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ['10.0.1.13:9100', '10.0.2.32:9100']
            
            - job_name: 'nginx'
              static_configs:
                - targets: ['10.0.1.13:4040', '10.0.2.32:4040']
        dest: /etc/prometheus/prometheus.yml

    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        ports:
          - "9090:9090"
        volumes:
          - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
        restart_policy: always